//*
// grpc contract definiton for location service api,
// consumed by internal services

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: api/proto/order/order.proto

package order

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FindAllNearbyOrderIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Radius   float64   `protobuf:"fixed64,2,opt,name=radius,proto3" json:"radius,omitempty"`
}

func (x *FindAllNearbyOrderIDsRequest) Reset() {
	*x = FindAllNearbyOrderIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_order_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllNearbyOrderIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNearbyOrderIDsRequest) ProtoMessage() {}

func (x *FindAllNearbyOrderIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNearbyOrderIDsRequest.ProtoReflect.Descriptor instead.
func (*FindAllNearbyOrderIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllNearbyOrderIDsRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *FindAllNearbyOrderIDsRequest) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type FindAllNearbyOrderIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderIds []string `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	Status   int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *FindAllNearbyOrderIDsReply) Reset() {
	*x = FindAllNearbyOrderIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_order_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllNearbyOrderIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNearbyOrderIDsReply) ProtoMessage() {}

func (x *FindAllNearbyOrderIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNearbyOrderIDsReply.ProtoReflect.Descriptor instead.
func (*FindAllNearbyOrderIDsReply) Descriptor() ([]byte, []int) {
	return file_api_proto_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllNearbyOrderIDsReply) GetOrderIds() []string {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

func (x *FindAllNearbyOrderIDsReply) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lon float64 `protobuf:"fixed64,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat float64 `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_order_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_proto_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

var File_api_proto_order_order_proto protoreflect.FileDescriptor

var file_api_proto_order_order_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e,
	0x65, 0x61, 0x72, 0x62, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x22, 0x51, 0x0a, 0x1a, 0x46, 0x69, 0x6e,
	0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2e, 0x0a, 0x08,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x32, 0x6f, 0x0a, 0x0c,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x15,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x73, 0x12, 0x23, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_order_order_proto_rawDescOnce sync.Once
	file_api_proto_order_order_proto_rawDescData = file_api_proto_order_order_proto_rawDesc
)

func file_api_proto_order_order_proto_rawDescGZIP() []byte {
	file_api_proto_order_order_proto_rawDescOnce.Do(func() {
		file_api_proto_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_order_order_proto_rawDescData)
	})
	return file_api_proto_order_order_proto_rawDescData
}

var file_api_proto_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_order_order_proto_goTypes = []interface{}{
	(*FindAllNearbyOrderIDsRequest)(nil), // 0: order.FindAllNearbyOrderIDsRequest
	(*FindAllNearbyOrderIDsReply)(nil),   // 1: order.FindAllNearbyOrderIDsReply
	(*Location)(nil),                     // 2: order.Location
}
var file_api_proto_order_order_proto_depIdxs = []int32{
	2, // 0: order.FindAllNearbyOrderIDsRequest.location:type_name -> order.Location
	0, // 1: order.OrderService.FindAllNearbyOrderIDs:input_type -> order.FindAllNearbyOrderIDsRequest
	1, // 2: order.OrderService.FindAllNearbyOrderIDs:output_type -> order.FindAllNearbyOrderIDsReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_order_order_proto_init() }
func file_api_proto_order_order_proto_init() {
	if File_api_proto_order_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_order_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllNearbyOrderIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_order_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllNearbyOrderIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_order_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_order_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_order_order_proto_goTypes,
		DependencyIndexes: file_api_proto_order_order_proto_depIdxs,
		MessageInfos:      file_api_proto_order_order_proto_msgTypes,
	}.Build()
	File_api_proto_order_order_proto = out.File
	file_api_proto_order_order_proto_rawDesc = nil
	file_api_proto_order_order_proto_goTypes = nil
	file_api_proto_order_order_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	FindAllNearbyOrderIDs(ctx context.Context, in *FindAllNearbyOrderIDsRequest, opts ...grpc.CallOption) (*FindAllNearbyOrderIDsReply, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) FindAllNearbyOrderIDs(ctx context.Context, in *FindAllNearbyOrderIDsRequest, opts ...grpc.CallOption) (*FindAllNearbyOrderIDsReply, error) {
	out := new(FindAllNearbyOrderIDsReply)
	err := c.cc.Invoke(ctx, "/order.OrderService/FindAllNearbyOrderIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	FindAllNearbyOrderIDs(context.Context, *FindAllNearbyOrderIDsRequest) (*FindAllNearbyOrderIDsReply, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) FindAllNearbyOrderIDs(context.Context, *FindAllNearbyOrderIDsRequest) (*FindAllNearbyOrderIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllNearbyOrderIDs not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_FindAllNearbyOrderIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllNearbyOrderIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).FindAllNearbyOrderIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/FindAllNearbyOrderIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).FindAllNearbyOrderIDs(ctx, req.(*FindAllNearbyOrderIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAllNearbyOrderIDs",
			Handler:    _OrderService_FindAllNearbyOrderIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/order/order.proto",
}
